# Generated by Django 5.2.3 on 2025-08-10 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_workout', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardioworkout',
            name='routine_difficulty',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
