# Generated by Django 5.2.3 on 2025-08-10 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_workout', '0002_cardioworkout_routine_difficulty'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cardioworkout',
            old_name='routine_difficulty',
            new_name='difficulty',
        ),
    ]
