# Generated by Django 5.2.3 on 2025-08-10 16:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_workout', '0003_rename_routine_difficulty_cardioworkout_difficulty'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cardiodailylog',
            name='routine',
        ),
        migrations.AddField(
            model_name='cardiodailylog',
            name='workout',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='daily_logs', to='app_workout.cardioworkout'),
            preserve_default=False,
        ),
    ]
