# Generated by Django 5.2.3 on 2025-08-10 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_workout', '0004_remove_cardiodailylog_routine_cardiodailylog_workout'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardiodailylog',
            name='avg_mph',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cardiodailylog',
            name='goal',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cardiodailylog',
            name='max_mph',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cardiodailylog',
            name='minutes_elapsed',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cardiodailylog',
            name='total_completed',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cardiodailylogdetail',
            name='running_miles',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cardiodailylogdetail',
            name='running_mph',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cardiodailylogdetail',
            name='running_seconds',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cardiodailylogdetail',
            name='treadmill_time_seconds',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cardioprogression',
            name='progression',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='strengthcurrentmax',
            name='current_max',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='strengthcurrentmaxdailyvolume',
            name='daily_volume',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='strengthcurrentmaxweeklyvolume',
            name='weekly_volume',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='strengthdailylog',
            name='max_weight',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='strengthdailylog',
            name='minutes_elapsed',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='strengthdailylogdetail',
            name='weight',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='supplementaldailylog',
            name='total_completed',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='supplementaldailylogdetail',
            name='unit_count',
            field=models.FloatField(),
        ),
    ]
