# Generated by Django 5.1.5 on 2025-08-25 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_workout", "0005_alter_cardiodailylog_avg_mph_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="strengthdailylog",
            name="rep_goal",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
