# Generated by Django 5.1.5 on 2025-08-25 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_workout", "0006_alter_strengthdailylog_rep_goal"),
    ]

    operations = [
        migrations.AlterField(
            model_name="strengthdailylog",
            name="total_reps_completed",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
