# Generated by Django 5.1.5 on 2025-08-25 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_workout", "0007_alter_strengthdailylog_total_reps_completed"),
    ]

    operations = [
        migrations.AddField(
            model_name="strengthexercise",
            name="bodyweight_percentage",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="strengthexercise",
            name="default_weight",
            field=models.FloatField(default=0),
        ),
    ]
