# Generated by Django 5.1.5 on 2025-08-25 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_workout", "0008_strengthexercise_bodyweight_percentage_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Bodyweight",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("bodyweight", models.FloatField(default=186)),
            ],
            options={
                "verbose_name": "Bodyweight",
                "verbose_name_plural": "Bodyweight",
            },
        ),
    ]
