# Generated by Django 5.1.5 on 2025-08-25 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app_workout", "0009_bodyweight"),
    ]

    operations = [
        migrations.RemoveField(model_name="strengthexercise", name="default_weight",),
    ]
