# Generated by Django 5.1.5 on 2025-08-27 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_workout", "0011_alter_strengthdailylog_max_reps"),
    ]

    operations = [
        migrations.CreateModel(
            name="VwMPHGoal",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=50, unique=True)),
                ("difficulty", models.PositiveIntegerField(default=1)),
                ("mph_goal", models.FloatField()),
            ],
            options={
                "db_table": "Vw_MPH_Goal",
                "ordering": ["difficulty", "id"],
                "managed": False,
            },
        ),
    ]
