# Generated by Django 5.1.5 on 2025-09-14 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_workout', '0014_cardiowarmupsettings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardiowarmupsettings',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
