# Generated by Django 5.1.5 on 2025-09-15 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_workout', '0016_cardioworkouttmsyncpreference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardioworkouttmsyncpreference',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
