# Generated by Django 5.1.5 on 2025-09-21 12:26

import django.db.models.deletion
from django.db import migrations, models


def copy_warmup_defaults(apps, schema_editor):
    WarmupSettings = apps.get_model("app_workout", "CardioWarmupSettings")
    WorkoutWarmup = apps.get_model("app_workout", "CardioWorkoutWarmup")
    Workout = apps.get_model("app_workout", "CardioWorkout")

    settings = None
    try:
        settings = WarmupSettings.objects.first()
    except Exception:
        settings = None
    if not settings:
        return

    workouts = Workout.objects.select_related("routine")
    warmup_objects = []
    for workout in workouts:
        routine_name = (workout.routine.name or "").lower() if workout.routine else ""
        if routine_name == "sprints":
            minutes = getattr(settings, "warmup_minutes_sprints", None)
            mph = getattr(settings, "warmup_mph_sprints", None)
        else:
            minutes = getattr(settings, "warmup_minutes_5k_prep", None)
            mph = getattr(settings, "warmup_mph_5k_prep", None)
        warmup_objects.append((workout, minutes, mph))

    for workout, minutes, mph in warmup_objects:
        WorkoutWarmup.objects.update_or_create(
            workout=workout,
            defaults={
                "warmup_minutes": minutes,
                "warmup_mph": mph,
            },
        )


class Migration(migrations.Migration):

    dependencies = [
        ('app_workout', '0017_alter_cardioworkouttmsyncpreference_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='CardioWorkoutWarmup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('warmup_minutes', models.FloatField(blank=True, null=True)),
                ('warmup_mph', models.FloatField(blank=True, null=True)),
                ('workout', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='warmup_pref', to='app_workout.cardioworkout')),
            ],
            options={
                'verbose_name': 'Cardio Workout Warmup',
                'verbose_name_plural': 'Cardio Workout Warmups',
                'ordering': ['workout__routine__name', 'workout__name'],
            },
        ),
        migrations.RunPython(copy_warmup_defaults, migrations.RunPython.noop),
        migrations.DeleteModel(
            name='CardioWarmupSettings',
        ),
        migrations.DeleteModel(
            name='VwMPHGoal',
        ),
    ]
