# Generated by Django 5.2.3 on 2025-09-21 22:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_workout', '0019_strengthdailylog_rph_goals'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='strengthcurrentmaxdailyvolume',
            name='routine',
        ),
        migrations.RemoveField(
            model_name='strengthcurrentmaxweeklyvolume',
            name='routine',
        ),
        migrations.DeleteModel(
            name='StrengthCurrentMax',
        ),
        migrations.DeleteModel(
            name='StrengthCurrentMaxDailyVolume',
        ),
        migrations.DeleteModel(
            name='StrengthCurrentMaxWeeklyVolume',
        ),
    ]
