# Generated by Django 5.1.5 on 2025-09-24 15:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_workout', '0021_strengthdailylog_max_reps_goal'),
    ]

    operations = [
        migrations.CreateModel(
            name='CardioWorkoutRestThreshold',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yellow_start_seconds', models.PositiveIntegerField(default=120)),
                ('red_start_seconds', models.PositiveIntegerField(default=180)),
                ('critical_start_seconds', models.PositiveIntegerField(default=300)),
                ('workout', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rest_threshold', to='app_workout.cardioworkout')),
            ],
            options={
                'verbose_name': 'Cardio Workout Rest Threshold',
                'verbose_name_plural': 'Cardio Workout Rest Thresholds',
                'ordering': ['workout__routine__name', 'workout__name'],
            },
        ),
        migrations.CreateModel(
            name='StrengthExerciseRestThreshold',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yellow_start_seconds', models.PositiveIntegerField(default=120)),
                ('red_start_seconds', models.PositiveIntegerField(default=180)),
                ('critical_start_seconds', models.PositiveIntegerField(default=300)),
                ('exercise', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rest_threshold', to='app_workout.strengthexercise')),
            ],
            options={
                'verbose_name': 'Strength Exercise Rest Threshold',
                'verbose_name_plural': 'Strength Exercise Rest Thresholds',
                'ordering': ['exercise__routine__name', 'exercise__name'],
            },
        ),
    ]
