# Generated by Django 5.1.5 on 2025-09-26 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_workout', '0022_cardioworkoutrestthreshold_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='strengthdailylog',
            name='max_weight_goal',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
