# Generated by Django 5.2.3 on 2025-11-24 19:37

from django.db import migrations, models


def copy_program_selected(apps, schema_editor):
    Program = apps.get_model('app_workout', 'Program')
    for program in Program.objects.all():
        selected = getattr(program, 'selected', False)
        program.selected_cardio = selected
        program.selected_strength = selected
        program.selected_supplemental = selected
        program.save(update_fields=['selected_cardio', 'selected_strength', 'selected_supplemental'])


class Migration(migrations.Migration):

    dependencies = [
        ('app_workout', '0023_strengthdailylog_max_weight_goal'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='strengthdailylogdetail',
            options={'ordering': ['-datetime', '-id'], 'verbose_name': 'Strength Daily Log Detail', 'verbose_name_plural': 'Strength Daily Log Details'},
        ),
        migrations.AddField(
            model_name='program',
            name='selected_cardio',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='program',
            name='selected_strength',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='program',
            name='selected_supplemental',
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(copy_program_selected, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='program',
            name='selected',
        ),
        migrations.AddConstraint(
            model_name='program',
            constraint=models.UniqueConstraint(condition=models.Q(selected_cardio=True), fields=('selected_cardio',), name='unique_selected_cardio'),
        ),
        migrations.AddConstraint(
            model_name='program',
            constraint=models.UniqueConstraint(condition=models.Q(selected_strength=True), fields=('selected_strength',), name='unique_selected_strength'),
        ),
        migrations.AddConstraint(
            model_name='program',
            constraint=models.UniqueConstraint(condition=models.Q(selected_supplemental=True), fields=('selected_supplemental',), name='unique_selected_supplemental'),
        ),
    ]
