# Generated by Django 5.2.3 on 2025-11-24 20:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_workout', '0024_alter_strengthdailylogdetail_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplementaldailylog',
            name='goal_metric',
            field=models.CharField(blank=True, choices=[('Max Unit', 'Max Unit'), ('Max Sets', 'Max Sets')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='supplementaldailylog',
            name='workout',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='daily_logs', to='app_workout.supplementalworkout'),
        ),
    ]
