# Generated by Django 5.2.3 on 2025-11-28 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_workout', '0025_supplementaldailylog_workout_goal_metric'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardiodailylog',
            name='ignore',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='strengthdailylog',
            name='ignore',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='supplementaldailylog',
            name='ignore',
            field=models.BooleanField(default=False),
        ),
    ]
