# Generated by Django 5.2.3 on 2025-12-02 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_workout', '0027_cardiodailylog_three_mile_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpecialRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skip_marathon_prep_weekdays', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Special Rule',
                'verbose_name_plural': 'Special Rules',
            },
        ),
    ]
