# Generated by Django 5.2.3 on 2025-12-22 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_workout', '0028_specialrule'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardioworkout',
            name='goal_distance',
            field=models.FloatField(default=0.75, help_text='The Distance for the goal'),
        ),
    ]
