# Generated by Django 5.2.3 on 2025-12-22 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_workout', '0029_cardioworkout_goal_distance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardioworkout',
            name='goal_distance',
            field=models.FloatField(default=3, help_text='The Distance for the goal'),
        ),
    ]
