# Generated by Django 5.2.3 on 2026-01-18 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_workout', '0033_specialrule_pyramid_rest_factors'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplementaldailylog',
            name='goal_set_1',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='supplementaldailylog',
            name='goal_set_2',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='supplementaldailylog',
            name='goal_set_3',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='supplementaldailylog',
            name='goal_weight_set_1',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='supplementaldailylog',
            name='goal_weight_set_2',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='supplementaldailylog',
            name='goal_weight_set_3',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='supplementaldailylog',
            name='rest_red_start_seconds',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='supplementaldailylog',
            name='rest_yellow_start_seconds',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='supplementaldailylogdetail',
            name='set_number',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='supplementaldailylogdetail',
            name='weight',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='supplementalroutine',
            name='max_set',
            field=models.FloatField(default=60.0),
        ),
        migrations.AddField(
            model_name='supplementalroutine',
            name='rest_red_start_seconds',
            field=models.PositiveIntegerField(default=90),
        ),
        migrations.AddField(
            model_name='supplementalroutine',
            name='rest_yellow_start_seconds',
            field=models.PositiveIntegerField(default=60),
        ),
        migrations.AddField(
            model_name='supplementalroutine',
            name='step_value',
            field=models.FloatField(default=5.0),
        ),
        migrations.AddField(
            model_name='supplementalroutine',
            name='step_weight',
            field=models.FloatField(default=5.0),
        ),
    ]
