# Generated by Django 5.2.3 on 2026-01-18 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_workout', '0034_supplementaldailylog_goal_set_1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supplementaldailylog',
            name='workout',
        ),
        migrations.RemoveField(
            model_name='supplementaldailylog',
            name='goal_metric',
        ),
        migrations.DeleteModel(
            name='SupplementalWorkoutDescription',
        ),
        migrations.DeleteModel(
            name='SupplementalWorkout',
        ),
    ]
