# Generated by Django 5.2.3 on 2026-02-15 18:15

import django.db.models.deletion
from django.db import migrations, models


def _seed_cardio_goal_rows(apps, schema_editor):
    CardioWorkout = apps.get_model("app_workout", "CardioWorkout")
    CardioGoals = apps.get_model("app_workout", "CardioGoals")

    existing_ids = set(CardioGoals.objects.values_list("workout_id", flat=True))
    missing = [
        CardioGoals(workout_id=workout_id)
        for workout_id in CardioWorkout.objects.values_list("id", flat=True)
        if workout_id not in existing_ids
    ]
    if missing:
        CardioGoals.objects.bulk_create(missing)


def _noop(apps, schema_editor):
    return None


class Migration(migrations.Migration):

    dependencies = [
        ('app_workout', '0036_specialrule_pick_priority_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='CardioGoals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mph_raw', models.JSONField(blank=True, default=dict)),
                ('mph_rounded', models.JSONField(blank=True, default=dict)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('workout', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='goal_metrics', to='app_workout.cardioworkout')),
            ],
            options={
                'verbose_name': 'Cardio Goal',
                'verbose_name_plural': 'Cardio Goals',
                'ordering': ['workout__routine__name', 'workout__name'],
            },
        ),
        migrations.RunPython(_seed_cardio_goal_rows, _noop),
    ]
