# Generated by Django 5.2.3 on 2026-02-15 18:20

from math import ceil, isfinite
from django.db import migrations, models


def _to_float(value):
    try:
        number = float(value)
    except (TypeError, ValueError):
        return None
    if not isfinite(number):
        return None
    return number


def _from_json_scalar_or_map(value, keys):
    if isinstance(value, dict):
        for key in keys:
            parsed = _to_float(value.get(key))
            if parsed is not None:
                return parsed
        return None
    return _to_float(value)


def _convert_json_mph_maps(apps, schema_editor):
    CardioGoals = apps.get_model("app_workout", "CardioGoals")

    upward_keys = [
        "upward_trend_threshold_max_mph_8weeks",
        "upward_trend_threshold_max_mph_6months",
    ]
    current_keys = [
        "current_trend_max_mph_8weeks",
        "current_trend_max_mph_6months",
    ]

    for row in CardioGoals.objects.all():
        raw_json = row.mph_raw
        rounded_json = row.mph_rounded

        upward = _from_json_scalar_or_map(raw_json, upward_keys)
        current = _from_json_scalar_or_map(raw_json, current_keys)
        mph_raw = upward if upward is not None else current

        mph_rounded = _from_json_scalar_or_map(rounded_json, upward_keys)
        if mph_rounded is None and mph_raw is not None:
            mph_rounded = ceil(mph_raw * 10.0) / 10.0

        # JSON fields are still non-null at this migration point, so keep a
        # numeric fallback for rows that previously had "{}".
        row.mph_raw = mph_raw if mph_raw is not None else 0.0
        row.mph_rounded = mph_rounded if mph_rounded is not None else 0.0
        row.upward_trend_threshold_mph = upward
        row.current_trend_mph = current
        row.save(
            update_fields=[
                "mph_raw",
                "mph_rounded",
                "upward_trend_threshold_mph",
                "current_trend_mph",
            ]
        )


def _noop(apps, schema_editor):
    return None


def _normalize_post_alter(apps, schema_editor):
    CardioGoals = apps.get_model("app_workout", "CardioGoals")
    CardioGoals.objects.filter(
        upward_trend_threshold_mph__isnull=True,
        current_trend_mph__isnull=True,
        mph_raw=0.0,
        mph_rounded=0.0,
    ).update(mph_raw=None, mph_rounded=None)


class Migration(migrations.Migration):

    dependencies = [
        ('app_workout', '0037_cardiogoals'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardiogoals',
            name='current_trend_mph',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cardiogoals',
            name='upward_trend_threshold_mph',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.RunPython(_convert_json_mph_maps, _noop),
        migrations.AlterField(
            model_name='cardiogoals',
            name='mph_raw',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cardiogoals',
            name='mph_rounded',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.RunPython(_normalize_post_alter, _noop),
    ]
