# Generated by Django 5.2.3 on 2026-02-15 18:27

import django.db.models.deletion
from django.db import migrations, models


GOAL_TYPES = [
    "highest_max_mph_6months",
    "highest_avg_mph_6months",
    "highest_max_mph_8weeks",
    "highest_avg_mph_8weeks",
    "last_max_mph",
    "last_avg_mph",
    "upward_trend_threshold_max_mph_6months",
    "upward_trend_threshold_avg_mph_6months",
    "upward_trend_threshold_max_mph_8weeks",
    "upward_trend_threshold_avg_mph_8weeks",
    "current_trend_max_mph_6months",
    "current_trend_avg_mph_6months",
    "current_trend_max_mph_8weeks",
    "current_trend_avg_mph_8weeks",
]


def _expand_and_sync_rows(apps, schema_editor):
    CardioGoals = apps.get_model("app_workout", "CardioGoals")

    existing_rows = list(CardioGoals.objects.all())
    seen = {(row.workout_id, row.goal_type) for row in existing_rows}
    to_create = []

    for row in existing_rows:
        for goal_type in GOAL_TYPES:
            key = (row.workout_id, goal_type)
            if key in seen:
                continue
            seen.add(key)
            to_create.append(
                CardioGoals(
                    workout_id=row.workout_id,
                    goal_type=goal_type,
                    mph_raw=row.mph_raw,
                    mph_rounded=row.mph_rounded,
                    inter_rank=row.inter_rank,
                )
            )

    if to_create:
        CardioGoals.objects.bulk_create(to_create)


def _noop(apps, schema_editor):
    return None


class Migration(migrations.Migration):

    dependencies = [
        ('app_workout', '0038_cardiogoals_current_trend_mph_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cardiogoals',
            options={'ordering': ['workout__routine__name', 'workout__name', 'goal_type'], 'verbose_name': 'Cardio Goal', 'verbose_name_plural': 'Cardio Goals'},
        ),
        migrations.RemoveField(
            model_name='cardiogoals',
            name='current_trend_mph',
        ),
        migrations.RemoveField(
            model_name='cardiogoals',
            name='upward_trend_threshold_mph',
        ),
        migrations.AddField(
            model_name='cardiogoals',
            name='goal_type',
            field=models.CharField(choices=[('highest_max_mph_6months', 'Highest Max MPH in Last 6 Months'), ('highest_avg_mph_6months', 'Highest Avg MPH in Last 6 Months'), ('highest_max_mph_8weeks', 'Highest Max MPH in Last 8 Weeks'), ('highest_avg_mph_8weeks', 'Highest Avg MPH in Last 8 Weeks'), ('last_max_mph', 'Last Max MPH'), ('last_avg_mph', 'Last Avg MPH'), ('upward_trend_threshold_max_mph_6months', 'Minimum Max MPH for Upward Trend (Last 6 Months)'), ('upward_trend_threshold_avg_mph_6months', 'Minimum Avg MPH for Upward Trend (Last 6 Months)'), ('upward_trend_threshold_max_mph_8weeks', 'Minimum Max MPH for Upward Trend (Last 8 Weeks)'), ('upward_trend_threshold_avg_mph_8weeks', 'Minimum Avg MPH for Upward Trend (Last 8 Weeks)'), ('current_trend_max_mph_6months', 'Current Max MPH Trend (Last 6 Months)'), ('current_trend_avg_mph_6months', 'Current Avg MPH Trend (Last 6 Months)'), ('current_trend_max_mph_8weeks', 'Current Max MPH Trend (Last 8 Weeks)'), ('current_trend_avg_mph_8weeks', 'Current Avg MPH Trend (Last 8 Weeks)')], default='upward_trend_threshold_max_mph_8weeks', max_length=64),
        ),
        migrations.AddField(
            model_name='cardiogoals',
            name='inter_rank',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cardiogoals',
            name='workout',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goal_metrics', to='app_workout.cardioworkout'),
        ),
        migrations.RunPython(_expand_and_sync_rows, _noop),
        migrations.AddConstraint(
            model_name='cardiogoals',
            constraint=models.UniqueConstraint(fields=('workout', 'goal_type'), name='uniq_cardiogoals_workout_goal_type'),
        ),
    ]
