# Generated by Django 5.2.3 on 2026-02-15 18:34

from django.db import migrations, models


def _populate_max_avg_type(apps, schema_editor):
    CardioGoals = apps.get_model("app_workout", "CardioGoals")
    for row in CardioGoals.objects.all().only("id", "goal_type"):
        goal_type = str(getattr(row, "goal_type", "") or "").lower()
        row.max_avg_type = "avg" if ("_avg_" in goal_type or goal_type.endswith("_avg_mph")) else "max"
        row.save(update_fields=["max_avg_type"])


def _resync_all_rows(apps, schema_editor):
    CardioWorkout = apps.get_model("app_workout", "CardioWorkout")
    from app_workout.cardio_goals_utils import sync_cardio_goals_for_workout

    for workout_id in CardioWorkout.objects.values_list("id", flat=True):
        sync_cardio_goals_for_workout(workout_id)


def _noop(apps, schema_editor):
    return None


class Migration(migrations.Migration):

    dependencies = [
        ('app_workout', '0039_alter_cardiogoals_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cardiogoals',
            options={'ordering': ['workout__routine__name', 'workout__name', 'max_avg_type', 'goal_type'], 'verbose_name': 'Cardio Goal', 'verbose_name_plural': 'Cardio Goals'},
        ),
        migrations.AddField(
            model_name='cardiogoals',
            name='max_avg_type',
            field=models.CharField(choices=[('max', 'Max'), ('avg', 'Avg')], default='max', max_length=3),
        ),
        migrations.RunPython(_populate_max_avg_type, _noop),
        migrations.RunPython(_resync_all_rows, _noop),
    ]
