# Generated by Django 5.2.3 on 2026-02-15 19:00

from django.db import migrations, models


def _sync_all_rows(apps, schema_editor):
    CardioWorkout = apps.get_model("app_workout", "CardioWorkout")
    from app_workout.cardio_goals_utils import sync_cardio_goals_for_workout

    for workout_id in CardioWorkout.objects.values_list("id", flat=True):
        sync_cardio_goals_for_workout(workout_id)


def _noop(apps, schema_editor):
    return None


class Migration(migrations.Migration):

    dependencies = [
        ('app_workout', '0041_alter_cardiogoals_goal_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardiogoals',
            name='goal_type',
            field=models.CharField(choices=[('highest_max_mph_6months', 'Highest Max MPH in Last 6 Months'), ('highest_avg_mph_6months', 'Highest Avg MPH in Last 6 Months'), ('highest_max_mph_8weeks', 'Highest Max MPH in Last 8 Weeks'), ('highest_avg_mph_8weeks', 'Highest Avg MPH in Last 8 Weeks'), ('last_max_mph', 'Last Max MPH'), ('last_avg_mph', 'Last Avg MPH'), ('upward_trend_threshold_max_mph_6months', 'Minimum Max MPH for Upward Trend (Last 6 Months)'), ('upward_trend_threshold_avg_mph_6months', 'Minimum Avg MPH for Upward Trend (Last 6 Months)'), ('upward_trend_threshold_max_mph_8weeks', 'Minimum Max MPH for Upward Trend (Last 8 Weeks)'), ('upward_trend_threshold_avg_mph_8weeks', 'Minimum Avg MPH for Upward Trend (Last 8 Weeks)'), ('current_trend_max_mph_6months', 'Current Max MPH Trend (Last 6 Months)'), ('current_trend_avg_mph_6months', 'Current Avg MPH Trend (Last 6 Months)'), ('current_trend_max_mph_8weeks', 'Current Max MPH Trend (Last 8 Weeks)'), ('current_trend_avg_mph_8weeks', 'Current Avg MPH Trend (Last 8 Weeks)'), ('riegel_predicted_max_mph_6months', 'Riegel Predicted Max MPH 6 Months (T2 = T1 * (D2 / D1)^1.06)'), ('riegel_predicted_avg_mph_6months', 'Riegel Predicted Avg MPH 6 Months (T2 = T1 * (D2 / D1)^1.06)'), ('riegel_predicted_max_mph_8weeks', 'Riegel Predicted Max MPH 8 Weeks (T2 = T1 * (D2 / D1)^1.06)'), ('riegel_predicted_avg_mph_8weeks', 'Riegel Predicted Avg MPH 8 Weeks (T2 = T1 * (D2 / D1)^1.06)')], default='upward_trend_threshold_max_mph_8weeks', max_length=64),
        ),
        migrations.RunPython(_sync_all_rows, _noop),
    ]
