# Generated by Django 5.2.3 on 2026-02-15 19:12

from django.db import migrations, models


def _resync_all_rows(apps, schema_editor):
    CardioWorkout = apps.get_model("app_workout", "CardioWorkout")
    from app_workout.cardio_goals_utils import sync_cardio_goals_for_workout

    for workout_id in CardioWorkout.objects.values_list("id", flat=True):
        sync_cardio_goals_for_workout(workout_id)


def _noop(apps, schema_editor):
    return None


class Migration(migrations.Migration):

    dependencies = [
        ('app_workout', '0042_alter_cardiogoals_goal_type'),
    ]

    operations = [
        migrations.RunPython(_resync_all_rows, _noop),
        migrations.AddConstraint(
            model_name='cardiogoals',
            constraint=models.UniqueConstraint(condition=models.Q(('mph_rounded__isnull', False)), fields=('workout', 'mph_rounded'), name='uniq_cardiogoals_workout_mph_rounded'),
        ),
    ]
