# Generated by Django 5.2.3 on 2026-02-15 22:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_workout', '0043_cardiogoals_uniq_cardiogoals_workout_mph_rounded'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cardioworkout',
            name='mph_goal_strategy',
        ),
    ]
