# Generated by Django 5.2.3 on 2026-02-16

import django.db.models.deletion
from django.db import migrations, models


STRENGTH_GOAL_TYPES = [
    "highest_max_rph_6months",
    "highest_avg_rph_6months",
    "highest_max_rph_8weeks",
    "highest_avg_rph_8weeks",
    "last_max_rph",
    "last_avg_rph",
    "upward_trend_threshold_max_rph_6months",
    "upward_trend_threshold_avg_rph_6months",
    "upward_trend_threshold_max_rph_8weeks",
    "upward_trend_threshold_avg_rph_8weeks",
    "current_trend_max_rph_6months",
    "current_trend_avg_rph_6months",
    "current_trend_max_rph_8weeks",
    "current_trend_avg_rph_8weeks",
]

SUPPLEMENTAL_GOAL_TYPES = [
    "highest_max_unit_6months",
    "highest_avg_unit_6months",
    "highest_max_unit_8weeks",
    "highest_avg_unit_8weeks",
    "last_max_unit",
    "last_avg_unit",
    "upward_trend_threshold_max_unit_6months",
    "upward_trend_threshold_avg_unit_6months",
    "upward_trend_threshold_max_unit_8weeks",
    "upward_trend_threshold_avg_unit_8weeks",
    "current_trend_max_unit_6months",
    "current_trend_avg_unit_6months",
    "current_trend_max_unit_8weeks",
    "current_trend_avg_unit_8weeks",
]


def _seed_strength_goal_rows(apps, schema_editor):
    StrengthRoutine = apps.get_model("app_workout", "StrengthRoutine")
    StrengthGoals = apps.get_model("app_workout", "StrengthGoals")

    seen = set(StrengthGoals.objects.values_list("routine_id", "goal_type"))
    to_create = []
    for routine_id in StrengthRoutine.objects.values_list("id", flat=True):
        for goal_type in STRENGTH_GOAL_TYPES:
            key = (routine_id, goal_type)
            if key in seen:
                continue
            seen.add(key)
            to_create.append(
                StrengthGoals(
                    routine_id=routine_id,
                    goal_type=goal_type,
                    max_avg_type="avg" if "_avg_" in goal_type else "max",
                )
            )
    if to_create:
        StrengthGoals.objects.bulk_create(to_create)


def _seed_supplemental_goal_rows(apps, schema_editor):
    SupplementalRoutine = apps.get_model("app_workout", "SupplementalRoutine")
    SupplementalGoals = apps.get_model("app_workout", "SupplementalGoals")

    seen = set(SupplementalGoals.objects.values_list("routine_id", "goal_type"))
    to_create = []
    for routine_id in SupplementalRoutine.objects.values_list("id", flat=True):
        for goal_type in SUPPLEMENTAL_GOAL_TYPES:
            key = (routine_id, goal_type)
            if key in seen:
                continue
            seen.add(key)
            to_create.append(
                SupplementalGoals(
                    routine_id=routine_id,
                    goal_type=goal_type,
                    max_avg_type="avg" if "_avg_" in goal_type else "max",
                )
            )
    if to_create:
        SupplementalGoals.objects.bulk_create(to_create)


def _resync_all_goal_rows(apps, schema_editor):
    from app_workout.strength_goals_utils import refresh_all_strength_goals
    from app_workout.supplemental_goals_utils import refresh_all_supplemental_goals

    refresh_all_strength_goals()
    refresh_all_supplemental_goals()


def _noop(apps, schema_editor):
    return None


class Migration(migrations.Migration):

    dependencies = [
        ("app_workout", "0045_cardiodailylog_goal_percentages"),
    ]

    operations = [
        migrations.CreateModel(
            name="StrengthGoals",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "goal_type",
                    models.CharField(
                        choices=[
                            ("highest_max_rph_6months", "Highest Max RPH in Last 6 Months"),
                            ("highest_avg_rph_6months", "Highest Avg RPH in Last 6 Months"),
                            ("highest_max_rph_8weeks", "Highest Max RPH in Last 8 Weeks"),
                            ("highest_avg_rph_8weeks", "Highest Avg RPH in Last 8 Weeks"),
                            ("last_max_rph", "Last Max RPH"),
                            ("last_avg_rph", "Last Avg RPH"),
                            (
                                "upward_trend_threshold_max_rph_6months",
                                "Minimum Max RPH for Upward Trend (Last 6 Months)",
                            ),
                            (
                                "upward_trend_threshold_avg_rph_6months",
                                "Minimum Avg RPH for Upward Trend (Last 6 Months)",
                            ),
                            (
                                "upward_trend_threshold_max_rph_8weeks",
                                "Minimum Max RPH for Upward Trend (Last 8 Weeks)",
                            ),
                            (
                                "upward_trend_threshold_avg_rph_8weeks",
                                "Minimum Avg RPH for Upward Trend (Last 8 Weeks)",
                            ),
                            (
                                "current_trend_max_rph_6months",
                                "Current Max RPH Trend (Last 6 Months)",
                            ),
                            (
                                "current_trend_avg_rph_6months",
                                "Current Avg RPH Trend (Last 6 Months)",
                            ),
                            (
                                "current_trend_max_rph_8weeks",
                                "Current Max RPH Trend (Last 8 Weeks)",
                            ),
                            (
                                "current_trend_avg_rph_8weeks",
                                "Current Avg RPH Trend (Last 8 Weeks)",
                            ),
                        ],
                        default="upward_trend_threshold_max_rph_8weeks",
                        max_length=64,
                    ),
                ),
                (
                    "max_avg_type",
                    models.CharField(
                        choices=[("max", "Max"), ("avg", "Avg")],
                        default="max",
                        max_length=3,
                    ),
                ),
                ("rph_raw", models.FloatField(blank=True, null=True)),
                ("rph_rounded", models.FloatField(blank=True, null=True)),
                ("inter_rank", models.PositiveIntegerField(blank=True, null=True)),
                ("last_updated", models.DateTimeField(auto_now=True)),
                (
                    "routine",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="goal_metrics",
                        to="app_workout.strengthroutine",
                    ),
                ),
            ],
            options={
                "verbose_name": "Strength Goal",
                "verbose_name_plural": "Strength Goals",
                "ordering": ["routine__name", "max_avg_type", "goal_type"],
            },
        ),
        migrations.CreateModel(
            name="SupplementalGoals",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "goal_type",
                    models.CharField(
                        choices=[
                            ("highest_max_unit_6months", "Highest Max Unit in Last 6 Months"),
                            ("highest_avg_unit_6months", "Highest Avg Unit in Last 6 Months"),
                            ("highest_max_unit_8weeks", "Highest Max Unit in Last 8 Weeks"),
                            ("highest_avg_unit_8weeks", "Highest Avg Unit in Last 8 Weeks"),
                            ("last_max_unit", "Last Max Unit"),
                            ("last_avg_unit", "Last Avg Unit"),
                            (
                                "upward_trend_threshold_max_unit_6months",
                                "Minimum Max Unit for Upward Trend (Last 6 Months)",
                            ),
                            (
                                "upward_trend_threshold_avg_unit_6months",
                                "Minimum Avg Unit for Upward Trend (Last 6 Months)",
                            ),
                            (
                                "upward_trend_threshold_max_unit_8weeks",
                                "Minimum Max Unit for Upward Trend (Last 8 Weeks)",
                            ),
                            (
                                "upward_trend_threshold_avg_unit_8weeks",
                                "Minimum Avg Unit for Upward Trend (Last 8 Weeks)",
                            ),
                            (
                                "current_trend_max_unit_6months",
                                "Current Max Unit Trend (Last 6 Months)",
                            ),
                            (
                                "current_trend_avg_unit_6months",
                                "Current Avg Unit Trend (Last 6 Months)",
                            ),
                            (
                                "current_trend_max_unit_8weeks",
                                "Current Max Unit Trend (Last 8 Weeks)",
                            ),
                            (
                                "current_trend_avg_unit_8weeks",
                                "Current Avg Unit Trend (Last 8 Weeks)",
                            ),
                        ],
                        default="upward_trend_threshold_max_unit_8weeks",
                        max_length=64,
                    ),
                ),
                (
                    "max_avg_type",
                    models.CharField(
                        choices=[("max", "Max"), ("avg", "Avg")],
                        default="max",
                        max_length=3,
                    ),
                ),
                ("unit_raw", models.FloatField(blank=True, null=True)),
                ("unit_rounded", models.FloatField(blank=True, null=True)),
                ("inter_rank", models.PositiveIntegerField(blank=True, null=True)),
                ("last_updated", models.DateTimeField(auto_now=True)),
                (
                    "routine",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="goal_metrics",
                        to="app_workout.supplementalroutine",
                    ),
                ),
            ],
            options={
                "verbose_name": "Supplemental Goal",
                "verbose_name_plural": "Supplemental Goals",
                "ordering": ["routine__name", "max_avg_type", "goal_type"],
            },
        ),
        migrations.RunPython(_seed_strength_goal_rows, _noop),
        migrations.RunPython(_seed_supplemental_goal_rows, _noop),
        migrations.RunPython(_resync_all_goal_rows, _noop),
        migrations.AddConstraint(
            model_name="strengthgoals",
            constraint=models.UniqueConstraint(
                fields=("routine", "goal_type"),
                name="uniq_strengthgoals_routine_goal_type",
            ),
        ),
        migrations.AddConstraint(
            model_name="strengthgoals",
            constraint=models.UniqueConstraint(
                condition=models.Q(("rph_rounded__isnull", False)),
                fields=("routine", "rph_rounded"),
                name="uniq_strengthgoals_routine_rph_rounded",
            ),
        ),
        migrations.AddConstraint(
            model_name="supplementalgoals",
            constraint=models.UniqueConstraint(
                fields=("routine", "goal_type"),
                name="uniq_supplementalgoals_routine_goal_type",
            ),
        ),
        migrations.AddConstraint(
            model_name="supplementalgoals",
            constraint=models.UniqueConstraint(
                condition=models.Q(("unit_rounded__isnull", False)),
                fields=("routine", "unit_rounded"),
                name="uniq_supplementalgoals_routine_unit_rounded",
            ),
        ),
    ]
