# Generated by ChatGPT on 2026-04-19

from django.conf import settings
from django.db import migrations, models
from zoneinfo import ZoneInfo


ROUTINE_SCHEDULE_SEEDS = [
    (1, ["5k_prep", "supplemental"]),
    (2, ["sprints", "strength"]),
    (3, ["5k_prep", "supplemental"]),
    (4, ["strength", "supplemental"]),
    (5, ["5k_prep", "supplemental"]),
    (6, ["sprints"]),
    (7, ["strength", "supplemental"]),
]


def _calendar_zone():
    tz_name = getattr(settings, "CALENDAR_TIME_ZONE", "America/Denver")
    try:
        return ZoneInfo(tz_name)
    except Exception:
        return ZoneInfo("America/Denver")


def _derive_activity_date(dt):
    if dt is None:
        return None
    return dt.astimezone(_calendar_zone()).date()


def _populate_log_day_fields(apps, schema_editor):
    CardioDailyLog = apps.get_model("app_workout", "CardioDailyLog")
    StrengthDailyLog = apps.get_model("app_workout", "StrengthDailyLog")
    SupplementalDailyLog = apps.get_model("app_workout", "SupplementalDailyLog")

    cardio_updates = []
    for log in CardioDailyLog.objects.all().only("id", "datetime_started", "activity_date"):
        log.activity_date = _derive_activity_date(log.datetime_started)
        cardio_updates.append(log)
    if cardio_updates:
        CardioDailyLog.objects.bulk_update(cardio_updates, ["activity_date"])

    strength_updates = []
    for log in StrengthDailyLog.objects.all().only("id", "datetime_started", "activity_date"):
        log.activity_date = _derive_activity_date(log.datetime_started)
        strength_updates.append(log)
    if strength_updates:
        StrengthDailyLog.objects.bulk_update(strength_updates, ["activity_date"])

    supplemental_updates = []
    for log in SupplementalDailyLog.objects.select_related("routine").all().only(
        "id",
        "datetime_started",
        "activity_date",
        "unit_snapshot",
        "routine__unit",
    ):
        log.activity_date = _derive_activity_date(log.datetime_started)
        log.unit_snapshot = getattr(log.routine, "unit", None)
        supplemental_updates.append(log)
    if supplemental_updates:
        SupplementalDailyLog.objects.bulk_update(
            supplemental_updates,
            ["activity_date", "unit_snapshot"],
        )


def _move_strength_related(StrengthExercise, StrengthDailyLog, StrengthPlan, StrengthGoals, source, target):
    if source is None or target is None or source.pk == target.pk:
        return

    StrengthExercise.objects.filter(routine_id=source.pk).update(routine_id=target.pk)
    StrengthDailyLog.objects.filter(routine_id=source.pk).update(routine_id=target.pk)

    for plan in list(StrengthPlan.objects.filter(routine_id=source.pk)):
        duplicate = StrengthPlan.objects.filter(program_id=plan.program_id, routine_id=target.pk).exclude(pk=plan.pk).exists()
        if duplicate:
            plan.delete()
        else:
            plan.routine_id = target.pk
            plan.save(update_fields=["routine"])

    StrengthGoals.objects.filter(routine_id=source.pk).delete()


def _merge_strength_routines(apps, schema_editor):
    StrengthRoutine = apps.get_model("app_workout", "StrengthRoutine")
    StrengthExercise = apps.get_model("app_workout", "StrengthExercise")
    StrengthDailyLog = apps.get_model("app_workout", "StrengthDailyLog")
    StrengthPlan = apps.get_model("app_workout", "StrengthPlan")
    StrengthGoals = apps.get_model("app_workout", "StrengthGoals")

    pull = StrengthRoutine.objects.filter(name="Pull").first()
    strength = StrengthRoutine.objects.filter(name="Strength").first()
    push = StrengthRoutine.objects.filter(name="Push").first()

    canonical = pull or strength or push
    if canonical is None:
        return

    if pull and strength and strength.pk != pull.pk:
        _move_strength_related(StrengthExercise, StrengthDailyLog, StrengthPlan, StrengthGoals, strength, pull)
        strength.delete()
        canonical = pull

    if push and push.pk != canonical.pk:
        _move_strength_related(StrengthExercise, StrengthDailyLog, StrengthPlan, StrengthGoals, push, canonical)
        push.delete()

    StrengthGoals.objects.filter(routine_id=canonical.pk).delete()
    if canonical.name != "Strength":
        canonical.name = "Strength"
        canonical.save(update_fields=["name"])


def _move_supplemental_related(SupplementalDailyLog, SupplementalPlan, SupplementalGoals, source, target):
    if source is None or target is None or source.pk == target.pk:
        return

    SupplementalDailyLog.objects.filter(routine_id=source.pk).update(routine_id=target.pk)

    for plan in list(SupplementalPlan.objects.filter(routine_id=source.pk)):
        duplicate = SupplementalPlan.objects.filter(program_id=plan.program_id, routine_id=target.pk).exclude(pk=plan.pk).exists()
        if duplicate:
            plan.delete()
        else:
            plan.routine_id = target.pk
            plan.save(update_fields=["routine"])

    SupplementalGoals.objects.filter(routine_id=source.pk).delete()


def _merge_supplemental_routines(apps, schema_editor):
    SupplementalRoutine = apps.get_model("app_workout", "SupplementalRoutine")
    SupplementalDailyLog = apps.get_model("app_workout", "SupplementalDailyLog")
    SupplementalPlan = apps.get_model("app_workout", "SupplementalPlan")
    SupplementalGoals = apps.get_model("app_workout", "SupplementalGoals")

    plank = SupplementalRoutine.objects.filter(name="Plank").first()
    supplemental = SupplementalRoutine.objects.filter(name="Supplemental").first()
    squat = SupplementalRoutine.objects.filter(name="Squat").first()

    canonical = plank or supplemental or squat
    if canonical is None:
        return

    if plank and supplemental and supplemental.pk != plank.pk:
        _move_supplemental_related(SupplementalDailyLog, SupplementalPlan, SupplementalGoals, supplemental, plank)
        supplemental.delete()
        canonical = plank

    if squat and squat.pk != canonical.pk:
        _move_supplemental_related(SupplementalDailyLog, SupplementalPlan, SupplementalGoals, squat, canonical)
        squat.delete()

    SupplementalGoals.objects.filter(routine_id=canonical.pk).delete()
    if canonical.name != "Supplemental":
        canonical.name = "Supplemental"
        canonical.save(update_fields=["name"])


def _cleanup_cardio_routines(apps, schema_editor):
    CardioRoutine = apps.get_model("app_workout", "CardioRoutine")
    CardioWorkout = apps.get_model("app_workout", "CardioWorkout")
    CardioPlan = apps.get_model("app_workout", "CardioPlan")
    CardioDailyLog = apps.get_model("app_workout", "CardioDailyLog")

    keep_names = {"5K Prep", "Sprints", "Rest"}
    five_k = CardioRoutine.objects.filter(name="5K Prep").first()
    sprints = CardioRoutine.objects.filter(name="Sprints").first()

    for routine in list(CardioRoutine.objects.exclude(name__in=keep_names)):
        name_lower = (routine.name or "").strip().lower()
        target = None
        if "sprint" in name_lower:
            target = sprints
        elif "5k" in name_lower or "marathon" in name_lower:
            target = five_k

        workout_ids = list(CardioWorkout.objects.filter(routine_id=routine.pk).values_list("id", flat=True))
        has_logs = bool(workout_ids and CardioDailyLog.objects.filter(workout_id__in=workout_ids).exists())

        if target and has_logs:
            CardioWorkout.objects.filter(routine_id=routine.pk).update(routine_id=target.pk)
            CardioPlan.objects.filter(routine_id=routine.pk).update(routine_id=target.pk)
            routine.delete()
            continue

        if not has_logs:
            CardioWorkout.objects.filter(routine_id=routine.pk).delete()
            CardioPlan.objects.filter(routine_id=routine.pk).delete()
            routine.delete()


def _seed_schedule_days(apps, schema_editor):
    RoutineScheduleDay = apps.get_model("app_workout", "RoutineScheduleDay")

    keep_ids = []
    for day_number, codes in ROUTINE_SCHEDULE_SEEDS:
        obj, _created = RoutineScheduleDay.objects.update_or_create(
            day_number=day_number,
            defaults={"routine_codes": list(codes)},
        )
        keep_ids.append(obj.pk)

    RoutineScheduleDay.objects.exclude(pk__in=keep_ids).delete()


def _refresh_goal_tables(apps, schema_editor):
    from app_workout.strength_goals_utils import refresh_all_strength_goals
    from app_workout.supplemental_goals_utils import refresh_all_supplemental_goals

    refresh_all_strength_goals()
    refresh_all_supplemental_goals()


def _forward_data(apps, schema_editor):
    _populate_log_day_fields(apps, schema_editor)
    _merge_strength_routines(apps, schema_editor)
    _merge_supplemental_routines(apps, schema_editor)
    _cleanup_cardio_routines(apps, schema_editor)
    _seed_schedule_days(apps, schema_editor)
    _refresh_goal_tables(apps, schema_editor)


def _noop(apps, schema_editor):
    return None


class Migration(migrations.Migration):

    dependencies = [
        ("app_workout", "0046_strengthgoals_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="cardiodailylog",
            name="activity_date",
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name="strengthdailylog",
            name="activity_date",
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name="supplementaldailylog",
            name="activity_date",
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name="supplementaldailylog",
            name="unit_snapshot",
            field=models.CharField(
                blank=True,
                choices=[("Time", "Time"), ("Reps", "Reps")],
                max_length=10,
                null=True,
            ),
        ),
        migrations.CreateModel(
            name="RoutineScheduleDay",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("day_number", models.PositiveSmallIntegerField(unique=True)),
                ("routine_codes", models.JSONField(default=list)),
            ],
            options={
                "verbose_name": "Routine Schedule Day",
                "verbose_name_plural": "Routine Schedule Days",
                "ordering": ["day_number"],
            },
        ),
        migrations.RunPython(_forward_data, _noop),
        migrations.AlterField(
            model_name="cardiodailylog",
            name="activity_date",
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name="strengthdailylog",
            name="activity_date",
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name="supplementaldailylog",
            name="activity_date",
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name="supplementaldailylog",
            name="unit_snapshot",
            field=models.CharField(choices=[("Time", "Time"), ("Reps", "Reps")], max_length=10),
        ),
    ]
