# Generated by Django 5.2.3 on 2026-04-19 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_workout', '0047_routinescheduleday_and_daily_activity'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CardioPlan',
        ),
        migrations.DeleteModel(
            name='CardioWorkoutWarmup',
        ),
        migrations.DeleteModel(
            name='StrengthPlan',
        ),
        migrations.DeleteModel(
            name='SupplementalPlan',
        ),
        migrations.DeleteModel(
            name='Program',
        ),
        migrations.DeleteModel(
            name='SpecialRule',
        ),
    ]
