# Generated by Django 5.2.3 on 2026-04-19 18:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_workout', '0048_alter_cardioplan_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyActivitySelection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_date', models.DateField(db_index=True, unique=True)),
                ('schedule_day', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='activity_selections', to='app_workout.routinescheduleday')),
            ],
            options={
                'verbose_name': 'Daily Activity Selection',
                'verbose_name_plural': 'Daily Activity Selections',
                'ordering': ['-activity_date'],
            },
        ),
    ]
