# Generated by Django 5.2.3 on 2026-04-19 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_workout', '0049_dailyactivityselection'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DailyActivitySelection',
        ),
    ]
