# Generated by Django 5.2.3 on 2026-04-20 00:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_workout', '0052_distanceconversionsettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='CardioMetricPeriodSelection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_key', models.CharField(max_length=32)),
                ('workout', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='metric_period_selection', to='app_workout.cardioworkout')),
            ],
            options={
                'verbose_name': 'Cardio Metric Period Selection',
                'verbose_name_plural': 'Cardio Metric Period Selections',
                'ordering': ['workout__routine__name', 'workout__priority_order', 'workout__name'],
            },
        ),
    ]
