# app_workout/urls.py
from django.urls import path
from .views import (
    NextCardioView,
    NextStrengthView,
    NextSupplementalView,
    CardioGoalView,
    StrengthGoalView,
    SupplementalGoalView,
    RoutinesOrderedView,
    WorkoutsOrderedView,
    PredictWorkoutForRoutineView,
    CardioMPHGoalView,
    CardioBestCompletedLogView,
    CardioBestCompletedAvgLogView,
    CardioDailyBasedPercentageLossView,
    CardioGoalDistanceView,
    CardioGoalDistanceUpdateView,
    CardioRestThresholdsView,
    CardioRestThresholdUpdateView,
    CardioProgressionsView,
    BodyweightView,
    DistanceConversionSettingsView,
    CardioDistributionView,
    CardioDistributionWorkoutTypesView,
    CardioMetricsView,
    TrainingTypeRecommendationView,
    AcceptDailyRecommendationView,
    LogCardioView,
    CardioExerciseListView,
    CardioLogsRecentView,
    CardioLogRetrieveView,
    CardioLogDetailsCreateView,
    CardioLogDetailUpdateView,
    CardioLogDestroyView,
    CardioLogDetailDestroyView,
    CardioUnitListView,
    CardioLogLastIntervalView,
    StrengthLogsRecentView,
    StrengthLogRetrieveView,
    StrengthLogDetailsCreateView,
    StrengthLogDetailUpdateView,
    StrengthLogDestroyView,
    StrengthLogDetailDestroyView,
    LogStrengthView,
    StrengthExerciseListView,
    StrengthLogLastSetView,
    CardioBackfillAllGapsView,
    CardioGoalsRefreshAllView,
    CardioGoalsTrendlineFitView,
    CardioTMSyncDefaultsView,
    CardioTMSyncDefaultUpdateView,
    StrengthRestThresholdsView,
    StrengthRestThresholdUpdateView,
    StrengthRepsPerHourGoalView,
    SupplementalLogsRecentView,
    SupplementalWorkoutDescriptionListView,
    SupplementalLogRetrieveView,
    SupplementalLogDetailsCreateView,
    SupplementalLogDetailUpdateView,
    SupplementalLogDestroyView,
    SupplementalLogDetailDestroyView,
    LogSupplementalView,
    SupplementalRoutineListView,
    WeeklyModelView,
)

urlpatterns = [
    path("cardio/next/", NextCardioView.as_view(), name="cardio-next"),
    path("strength/next/", NextStrengthView.as_view(), name="strength-next"),
    path("supplemental/next/", NextSupplementalView.as_view(), name="supplemental-next"),
    path("cardio/goal/", CardioGoalView.as_view(), name="cardio-goal"),
    path("strength/goal/", StrengthGoalView.as_view(), name="strength-goal"),
    path("cardio/routines-ordered/", RoutinesOrderedView.as_view(), name="cardio-routines-ordered"),
    path("cardio/workouts-ordered/", WorkoutsOrderedView.as_view(), name="cardio-workouts-ordered"),
    path("cardio/predict-workout/", PredictWorkoutForRoutineView.as_view(), name="cardio-predict-workout"),
    path("cardio/mph-goal/", CardioMPHGoalView.as_view(), name="cardio-mph-goal"),
    path("cardio/best-completed-log/", CardioBestCompletedLogView.as_view(), name="cardio-best-completed-log"),
    path("cardio/best-completed-avg-log/", CardioBestCompletedAvgLogView.as_view(), name="cardio-best-completed-avg-log"),
    path("cardio/daily-based-percentage-loss/", CardioDailyBasedPercentageLossView.as_view(), name="cardio-daily-based-percentage-loss"),
    path("strength/rph-goal/", StrengthRepsPerHourGoalView.as_view(), name="strength-rph-goal"),
    path("supplemental/goal/", SupplementalGoalView.as_view(), name="supplemental-goal"),
    path("strength/rest-thresholds/", StrengthRestThresholdsView.as_view(), name="strength-rest-thresholds"),
    path("strength/rest-thresholds/<int:exercise_id>/", StrengthRestThresholdUpdateView.as_view(), name="strength-rest-threshold-update"),
    path("cardio/goal-distances/", CardioGoalDistanceView.as_view(), name="cardio-goal-distances"),
    path("cardio/goal-distances/<int:workout_id>/", CardioGoalDistanceUpdateView.as_view(), name="cardio-goal-distance-update"),
    path("cardio/rest-thresholds/", CardioRestThresholdsView.as_view(), name="cardio-rest-thresholds"),
    path("cardio/rest-thresholds/<int:workout_id>/", CardioRestThresholdUpdateView.as_view(), name="cardio-rest-threshold-update"),
    path("cardio/progressions/", CardioProgressionsView.as_view(), name="cardio-progressions"),
    path("cardio/distribution/workout-types/", CardioDistributionWorkoutTypesView.as_view(), name="cardio-distribution-workout-types"),
    path("cardio/distribution/", CardioDistributionView.as_view(), name="cardio-distribution"),
    path("cardio/bodyweight/", BodyweightView.as_view(), name="cardio-bodyweight"),
    path("settings/distance-conversions/", DistanceConversionSettingsView.as_view(), name="distance-conversion-settings"),
    path("settings/weekly-model/", WeeklyModelView.as_view(), name="weekly-model"),
    path("metrics/cardio/", CardioMetricsView.as_view(), name="cardio-metrics"),
    path("home/recommendation/", TrainingTypeRecommendationView.as_view(), name="home-recommendation"),
    path("home/recommendation/accept/", AcceptDailyRecommendationView.as_view(), name="home-recommendation-accept"),

    path("cardio/logs/", CardioLogsRecentView.as_view(), name="cardio-logs-recent"),
    path("cardio/log/<int:pk>/", CardioLogRetrieveView.as_view(), name="cardio-log-retrieve"),
    path("cardio/log/<int:pk>/details/", CardioLogDetailsCreateView.as_view(), name="cardio-log-details-create"),
    path("cardio/log/<int:pk>/details/<int:detail_id>/", CardioLogDetailUpdateView.as_view(), name="cardio-log-detail-update"),
    path("cardio/log/<int:pk>/last-interval/", CardioLogLastIntervalView.as_view(), name="cardio-log-last-interval"),

    # NEW deletes
    path("cardio/log/<int:pk>/delete/", CardioLogDestroyView.as_view(), name="cardio-log-delete"),
    path("cardio/log/<int:pk>/details/<int:detail_id>/delete/", CardioLogDetailDestroyView.as_view(), name="cardio-log-detail-delete"),

    path("cardio/log/", LogCardioView.as_view(), name="cardio-log"),
    path("cardio/exercises/", CardioExerciseListView.as_view(), name="cardio-exercises"),
    path("cardio/backfill/all/", CardioBackfillAllGapsView.as_view(), name="cardio-backfill-all"),
    path("cardio/goals/refresh-all/", CardioGoalsRefreshAllView.as_view(), name="cardio-goals-refresh-all"),
    path("cardio/goals/trendline-fit/", CardioGoalsTrendlineFitView.as_view(), name="cardio-goals-trendline-fit"),

    path("cardio/units/", CardioUnitListView.as_view(), name="cardio-units"),
    path("cardio/tm-sync-defaults/", CardioTMSyncDefaultsView.as_view(), name="cardio-tm-sync-defaults"),
    path("cardio/tm-sync-defaults/<int:workout_id>/", CardioTMSyncDefaultUpdateView.as_view(), name="cardio-tm-sync-default-update"),

    path("strength/logs/", StrengthLogsRecentView.as_view(), name="strength-logs-recent"),
    path("strength/log/<int:pk>/", StrengthLogRetrieveView.as_view(), name="strength-log-retrieve"),
    path("strength/log/<int:pk>/details/", StrengthLogDetailsCreateView.as_view(), name="strength-log-details-create"),
    path("strength/log/<int:pk>/details/<int:detail_id>/", StrengthLogDetailUpdateView.as_view(), name="strength-log-detail-update"),
    path("strength/log/<int:pk>/last-set/", StrengthLogLastSetView.as_view(), name="strength-log-last-set"),
    path("strength/log/<int:pk>/delete/", StrengthLogDestroyView.as_view(), name="strength-log-delete"),
    path("strength/log/<int:pk>/details/<int:detail_id>/delete/", StrengthLogDetailDestroyView.as_view(), name="strength-log-detail-delete"),
    path("strength/log/", LogStrengthView.as_view(), name="strength-log"),
    path("strength/exercises/", StrengthExerciseListView.as_view(), name="strength-exercises"),
    path("supplemental/workouts/", SupplementalWorkoutDescriptionListView.as_view(), name="supplemental-workouts"),
    path("supplemental/routines/", SupplementalRoutineListView.as_view(), name="supplemental-routines"),
    path("supplemental/log/", LogSupplementalView.as_view(), name="supplemental-log"),
    path("supplemental/logs/", SupplementalLogsRecentView.as_view(), name="supplemental-logs-recent"),
    path("supplemental/log/<int:pk>/", SupplementalLogRetrieveView.as_view(), name="supplemental-log-retrieve"),
    path("supplemental/log/<int:pk>/details/", SupplementalLogDetailsCreateView.as_view(), name="supplemental-log-details-create"),
    path("supplemental/log/<int:pk>/details/<int:detail_id>/", SupplementalLogDetailUpdateView.as_view(), name="supplemental-log-detail-update"),
    path("supplemental/log/<int:pk>/delete/", SupplementalLogDestroyView.as_view(), name="supplemental-log-delete"),
    path("supplemental/log/<int:pk>/details/<int:detail_id>/delete/", SupplementalLogDetailDestroyView.as_view(), name="supplemental-log-detail-delete"),
]






